## 해파리 주간동향 크롤링

### 출현 해역 + 미출현 포함

__freq 구분__

0 : 미출현

1 : 단순 출현

2 : 저밀도 출현

3 : 고밀도 출현

In [134]:
# 날짜 리스트 만들기
from datetime import timedelta
from datetime import date

keyword_list = []


# 여기 날짜 수정 or input으로 받기

s_y, s_m, s_d = input('시작 날짜를 입력 (ex: 2021/12/01): ').split('/')
e_y, e_m, e_d = input('끝 날짜를 입력 - 존재하는 페이지 날짜로 (ex: 2022/06/30): ').split('/')


start = date(int(s_y), int(s_m), int(s_d))
end = date(int(e_y), int(e_m), int(e_d))


while end >= start:
    keyword_list.append(str(end).replace('-', '')+'00')
    end = end - timedelta(weeks=1)
    
    

    
# 그냥 정보 크롤링 부분
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
import re


# 2차원 리스트 -> 1차원 리스트
def flatten(lst):
    result = []
    for item in lst:
        result.extend(item)
    return result



region = input('지역 입력 (ex: 부산) : ')


df = pd.DataFrame(columns = ['date', 'sea', 'htype', 'percent', 'freq'])
keyword_idx = []

for keyword in keyword_list:
    url = 'https://www.nifs.go.kr/jelly/jemoNewsView.jely?news_seq='+keyword
    header = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36'}
    response = requests.get(url, headers = header)
    html_text = response.text
    
    if len(html_text) == 7043: # 없는 날짜면 길이가 7043 (틀이 정해져 있고, 그 틀의 길이)
        pass
        
    
    else:
        
        soup = BeautifulSoup(html_text, 'html.parser')

        table = soup.find_all('table', attrs={'class':'table_style_04'})
        tr = table[1].find_all('tr')
        
        for idx in range(2, len(tr)):
            td = tr[idx].find_all('td')
            
            # 해파리 종류 - char
            htype = td[0].find('b').get_text()
            
            # 발견률 - floast
            percent = float(re.findall('\d{0,2}[.]{0,1}\d{0,2}[%]', td[2].get_text().split('\r')[0])[0].replace('%', ''))
            
            # 독성 -  char
            poison = td[3].get_text()
            
            # 해파리 종류 + 독성 - char
            h_type = htype + '_' + poison
            
            
            wheret = td[1].get_text().split('\r')
            
            
            ## 예외처리 2018060700
            if '？' in wheret[0]:
                for i in range(len(wheret)):
                    wheret[i] = wheret[i].replace('？', ' ')
                    wheret[i] = wheret[i].replace('\n', '')

                    if '고밀도' in wheret[i] or '저밀도' in wheret[i]:
                        wheret[i] = '○' + wheret[i]

                    if '○' not in wheret[i] and '-' not in wheret[i]:
                        wheret[i] = '-' + wheret[i]

                wheret = [i for i in wheret if i != '-']

            
            
            
            for i in range(len(wheret)):
                if '(' in wheret[i]:
                    wheret[i] = re.sub(r'\([^)]*\)', '', wheret[i])
            
            
            ## 해역 이름 수정
            
            wheret = [i.strip() for i  in wheret]
            wheret = [i.replace('.', ',') for i  in wheret]
            wheret = [i for i in wheret if i !='']
            wheret = [i for i in wheret if '※' not in i]
            
            # 어떤 날짜에서는 , 다음에 -붙은채로 이어져야 하는게 있는 경우도... 수정
            for i in range(len(wheret)):
                
                if wheret[i][-1] == ',' and '○' not in wheret[i] and region in wheret[i+1]:
                    wheret[i] = wheret[i].replace(',', '')
                elif wheret[i][-1] == ',' and '○' not in wheret[i]:
                    wheret[i+1] = wheret[i+1].replace('-', '')
                else:
                    pass
                    
            
            # - 없는 애들 다 붙이기
            for t in range(len(wheret)-1, -1, -1):

                if '-' in wheret[t] or '•' in wheret[t] or '○' in wheret[t] or '◎' in wheret[t]:
                    pass
                else:
                    wheret[t-1] = wheret[t-1] +', '+ wheret[t]
                    wheret[t] = 0
                    
            wheret1 = [i for i in wheret if i != 0]
            
            
            wheret1 = [i.replace('․', '') for i in wheret1]
            wheret1 = [i.replace(',,', ',') for i in wheret1]
            
            
            
            # 합친 애들 다시 나눠서 이름 예쁘게 붙여주기
            index = []
            for i in range(len(wheret1)):
                if '-' in wheret1[i]:
                    index.append(i)


            wheret2 = [i.split(', ') for i in wheret1]
            
            for i in index:
    
                if len(wheret2[i][0].split(' ')) >= 4:
                    middle = wheret2[i][0].split(' ')[2] + ' '
                else:
                    middle = ''
                    
                
                for j in range(1, len(wheret2[i])):
                

                    if len(wheret2[i][j].split(' ')) >= 2:
                        if region in wheret2[i][j].split(' '):
                            pass
                        else:
                            wheret2[i][j] = '- ' + wheret2[i][0].split(' ')[1] +' '+ wheret2[i][j]
                            middle = wheret2[i][j].split(' ')[2] +' '

                    if len(wheret2[i][j].split(' ')) == 1:
                        wheret2[i][j] = '- ' + wheret2[i][0].split(' ')[1] +' '+ middle+ wheret2[i][j]

            
            wheret4 = flatten(wheret2)
    
            

            
            # 이름 정리 완성본
            f_wheret = wheret4
            f_wheret = [item.replace('  ', ' ') for item in f_wheret]
            
            
            # stopword 선정 후 제거
            f_wheret = [i.replace(' 연안', '') for i in f_wheret]
            f_wheret = [i.replace(' 부근', '') for i in f_wheret]
            f_wheret = [i.replace(' 등대', '') for i in f_wheret]
            f_wheret = [i.replace(' 연근해', '') for i in f_wheret]
            f_wheret = [i.replace(' 근해', '') for i in f_wheret]
            f_wheret = [i.replace('앞', '') for i in f_wheret]
            f_wheret = [i.replace('해변', '') for i in f_wheret]
            f_wheret = [i.replace('해수욕장', '') for i in f_wheret]

            
            # 중복되는 애들 제거
            wheret5 = f_wheret
        
            for i in range(len(wheret5)):
                if '-' in wheret5[i]:
                    for j in range(i+1, len(wheret5)):
                        if '-' in wheret5[j]:
                            if wheret5[i] == wheret5[j]:
                                wheret5[j] = '0'
                        else:
                            break

            
            wheret6 = [item for item in wheret5 if item != '0']
            
            

            
            
            
            f_wheret = [item.replace('-', '').strip() for item in wheret6]
            
            
            
            
            
            
            for i in range(len(f_wheret)):
                if region in f_wheret[i] and '출현' not in f_wheret[i]:

                    
                    seaname = f_wheret[i]
                    freq = 1 # 고밀도 저밀도 없으면 1
                    
                    for j in range(i-1, -1, -1):
                        
                        if '고밀도' in f_wheret[j]:
                            freq = 3
                            break
                            
                        elif '저밀도' in f_wheret[j]:
                            freq = 2
                            break
                            
                        
                            
                    # 데이터프레임에 넣어주는 작업
                    to_insert = {'date' : keyword[:-2],
                                 'sea' : seaname,
                                 'htype' : h_type,
                                 'percent' : percent,
                                 'freq' : freq}
                    
                    if len(df[(df.date == keyword[:-2]) & (df.sea == seaname) & (df.htype == h_type)]) == 0:
                        
                        df = df.append(to_insert, ignore_index = True)
                        
                    elif len(df[(df.date == keyword[:-2]) & (df.sea == seaname) & (df.htype == h_type)]) == 1:
                        if df[(df.date == keyword[:-2]) & (df.sea == seaname) & (df.htype == h_type)].freq.tolist()[0] < freq:
                            
                            df = df.append(to_insert, ignore_index = True)
                    
                
        print(keyword + ' is done.')
                            
                        
                        
                        
df

시작 날짜를 입력 (ex: 2021/12/01): 2017/03/01
끝 날짜를 입력 - 존재하는 페이지 날짜로 (ex: 2022/06/30): 2022/06/30
지역 입력 (ex: 부산) : 부산
2022063000 is done.
2022062300 is done.
2022061600 is done.
2022060900 is done.
2022060200 is done.
2022052600 is done.
2022051900 is done.
2022051200 is done.
2021120900 is done.
2021120200 is done.
2021112500 is done.
2021111800 is done.
2021111100 is done.
2021110400 is done.
2021102800 is done.
2021102100 is done.
2021101400 is done.
2021100700 is done.
2021093000 is done.
2021092300 is done.
2021091600 is done.
2021090900 is done.
2021090200 is done.
2021082600 is done.
2021081900 is done.
2021081200 is done.
2021080500 is done.
2021072900 is done.
2021072200 is done.
2021071500 is done.
2021070800 is done.
2021070100 is done.
2021062400 is done.
2021061700 is done.
2021061000 is done.
2021060300 is done.
2021052700 is done.
2021052000 is done.
2021051300 is done.
2021050600 is done.
2020121000 is done.
2020120300 is done.
2020112600 is done.
2020111900 is done.
2020111200 is done.
2020110500 is done.
2020102900 is done.
2020102200 is done.
2020101500 is done.
2020100800 is done.
2020092400 is done.
2020091700 is done.
2020091000 is done.
2020090300 is done.
2020082700 is done.
2020082000 is done.
2020081300 is done.
2020080600 is done.
2020073000 is done.
2020072300 is done.
2020071600 is done.
2020070900 is done.
2020070200 is done.
2020062500 is done.
2020061800 is done.
2020061100 is done.
2020060400 is done.
2020052800 is done.
2020052100 is done.
2020051400 is done.
2020050700 is done.
2019121200 is done.
2019120500 is done.
2019112800 is done.
2019112100 is done.
2019111400 is done.
2019110700 is done.
2019103100 is done.
2019102400 is done.
2019101700 is done.
2019101000 is done.
2019092600 is done.
2019091900 is done.
2019090500 is done.
2019082900 is done.
2019082200 is done.
2019080800 is done.
2019080100 is done.
2019072500 is done.
2019071800 is done.
2019071100 is done.
2019070400 is done.
2019062700 is done.
2019062000 is done.
2019053000 is done.
2019052300 is done.
2019051600 is done.
2019050900 is done.
2018121300 is done.
2018120600 is done.
2018112900 is done.
2018112200 is done.
2018111500 is done.
2018110800 is done.
2018110100 is done.
2018102500 is done.
2018101800 is done.
2018101100 is done.
2018100400 is done.
2018092000 is done.
2018091300 is done.
2018090600 is done.
2018083000 is done.
2018082300 is done.
2018081600 is done.
2018080900 is done.
2018080200 is done.
2018072600 is done.
2018071900 is done.
2018071200 is done.
2018070500 is done.
2018062800 is done.
2018062100 is done.
2018061400 is done.
2018060700 is done.
2018053100 is done.
2018052400 is done.
2018051700 is done.
2018051000 is done.
2017121400 is done.
2017120700 is done.
2017113000 is done.
2017112300 is done.
2017111600 is done.
2017110900 is done.
2017110200 is done.
2017102600 is done.
2017101900 is done.
2017101200 is done.
2017092800 is done.
2017092100 is done.
2017091400 is done.
2017090700 is done.
2017083100 is done.
2017082400 is done.
2017081700 is done.
2017081000 is done.
2017080300 is done.
2017072700 is done.
2017072000 is done.
2017071300 is done.
2017070600 is done.
2017062900 is done.
2017062200 is done.
2017061500 is done.
2017060800 is done.
2017060100 is done.
2017052500 is done.
2017051800 is done.
2017051100 is done.

         date      sea         htype  percent freq
0    20220630   부산 태종대  노무라입깃해파리_강독성     8.00    2
1    20220630  부산 북형제도  노무라입깃해파리_강독성     8.00    2
2    20220630   부산 가덕도   보름달물해파리_약독성    35.70    2
3    20220630    부산 영도   보름달물해파리_약독성    35.70    2
4    20220630   부산 광안리   보름달물해파리_약독성    35.70    2
..        ...      ...           ...      ...  ...
842  20170525    부산 생도   보름달물해파리_약독성    11.54    2
843  20170525   부산 광안리   보름달물해파리_약독성    11.54    2
844  20170518    부산 생도   보름달물해파리_약독성    11.54    3
845  20170511  부산 고리원전   보름달물해파리_약독성    11.54    2
846  20170511   부산 가덕도   보름달물해파리_약독성    11.54    2

[847 rows x 5 columns]

#### 미출현 추가 코드

In [146]:
df1 = df
df1

         date      sea         htype  percent freq
0    20220630   부산 태종대  노무라입깃해파리_강독성     8.00    2
1    20220630  부산 북형제도  노무라입깃해파리_강독성     8.00    2
2    20220630   부산 가덕도   보름달물해파리_약독성    35.70    2
3    20220630    부산 영도   보름달물해파리_약독성    35.70    2
4    20220630   부산 광안리   보름달물해파리_약독성    35.70    2
..        ...      ...           ...      ...  ...
842  20170525    부산 생도   보름달물해파리_약독성    11.54    2
843  20170525   부산 광안리   보름달물해파리_약독성    11.54    2
844  20170518    부산 생도   보름달물해파리_약독성    11.54    3
845  20170511  부산 고리원전   보름달물해파리_약독성    11.54    2
846  20170511   부산 가덕도   보름달물해파리_약독성    11.54    2

[847 rows x 5 columns]

In [147]:
for keyword in keyword_list:
    
    df_date = df1[df1.date == keyword[:-2]]
    percent = 0
    freq = 0
    
    for seaname in df1.sea.unique().tolist():
        
        # 해역 자체가 존재하지 않으면 모든 해파리에 관하여 내용 넣기
        if seaname not in df_date.sea.unique().tolist():
            for h_type in df1.htype.unique().tolist():
                to_insert = {'date' : keyword[:-2],
                             'sea' : seaname,
                             'htype' : h_type,
                             'percent' : percent,
                             'freq' : freq}
                df1 = df1.append(to_insert, ignore_index = True)
                
        else:
            
            df_sea = df_date[df1.sea == seaname]
            
            for h_type in df1.htype.unique().tolist():
                if h_type not in df_sea.htype.unique().tolist():
                    to_insert = {'date' : keyword[:-2],
                                 'sea' : seaname,
                                 'htype' : h_type,
                                 'percent' : percent,
                                 'freq' : freq}
                    df1 = df1.append(to_insert, ignore_index = True)
                    
                    
    print(keyword + ' is done.')

C:\Users\edr2\anaconda3\envs\edu\lib\site-packages\ipykernel_launcher.py:21: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

2022063000 is done.
2022062300 is done.
2022061600 is done.
2022060900 is done.
2022060200 is done.
2022052600 is done.
2022051900 is done.
2022051200 is done.
2022050500 is done.
2022042800 is done.
2022042100 is done.
2022041400 is done.
2022040700 is done.
2022033100 is done.
2022032400 is done.
2022031700 is done.
2022031000 is done.
2022030300 is done.
2022022400 is done.
2022021700 is done.
2022021000 is done.
2022020300 is done.
2022012700 is done.
2022012000 is done.
2022011300 is done.
2022010600 is done.
2021123000 is done.
2021122300 is done.
2021121600 is done.
2021120900 is done.
2021120200 is done.
2021112500 is done.
2021111800 is done.
2021111100 is done.
2021110400 is done.
2021102800 is done.
2021102100 is done.
2021101400 is done.
2021100700 is done.
2021093000 is done.
2021092300 is done.
2021091600 is done.
2021090900 is done.
2021090200 is done.
2021082600 is done.
2021081900 is done.
2021081200 is done.
2021080500 is done.
2021072900 is done.
2021072200 is done.
2021071500 is done.
2021070800 is done.
2021070100 is done.
2021062400 is done.
2021061700 is done.
2021061000 is done.
2021060300 is done.
2021052700 is done.
2021052000 is done.
2021051300 is done.
2021050600 is done.
2021042900 is done.
2021042200 is done.
2021041500 is done.
2021040800 is done.
2021040100 is done.
2021032500 is done.
2021031800 is done.
2021031100 is done.
2021030400 is done.
2021022500 is done.
2021021800 is done.
2021021100 is done.
2021020400 is done.
2021012800 is done.
2021012100 is done.
2021011400 is done.
2021010700 is done.
2020123100 is done.
2020122400 is done.
2020121700 is done.
2020121000 is done.
2020120300 is done.
2020112600 is done.
2020111900 is done.
2020111200 is done.
2020110500 is done.
2020102900 is done.
2020102200 is done.
2020101500 is done.
2020100800 is done.
2020100100 is done.
2020092400 is done.
2020091700 is done.
2020091000 is done.
2020090300 is done.
2020082700 is done.
2020082000 is done.
2020081300 is done.
2020080600 is done.
2020073000 is done.
2020072300 is done.
2020071600 is done.
2020070900 is done.
2020070200 is done.
2020062500 is done.
2020061800 is done.
2020061100 is done.
2020060400 is done.
2020052800 is done.
2020052100 is done.
2020051400 is done.
2020050700 is done.
2020043000 is done.
2020042300 is done.
2020041600 is done.
2020040900 is done.
2020040200 is done.
2020032600 is done.
2020031900 is done.
2020031200 is done.
2020030500 is done.
2020022700 is done.
2020022000 is done.
2020021300 is done.
2020020600 is done.
2020013000 is done.
2020012300 is done.
2020011600 is done.
2020010900 is done.
2020010200 is done.
2019122600 is done.
2019121900 is done.
2019121200 is done.
2019120500 is done.
2019112800 is done.
2019112100 is done.
2019111400 is done.
2019110700 is done.
2019103100 is done.
2019102400 is done.
2019101700 is done.
2019101000 is done.
2019100300 is done.
2019092600 is done.
2019091900 is done.
2019091200 is done.
2019090500 is done.
2019082900 is done.
2019082200 is done.
2019081500 is done.
2019080800 is done.
2019080100 is done.
2019072500 is done.
2019071800 is done.
2019071100 is done.
2019070400 is done.
2019062700 is done.
2019062000 is done.
2019061300 is done.
2019060600 is done.
2019053000 is done.
2019052300 is done.
2019051600 is done.
2019050900 is done.
2019050200 is done.
2019042500 is done.
2019041800 is done.
2019041100 is done.
2019040400 is done.
2019032800 is done.
2019032100 is done.
2019031400 is done.
2019030700 is done.
2019022800 is done.
2019022100 is done.
2019021400 is done.
2019020700 is done.
2019013100 is done.
2019012400 is done.
2019011700 is done.
2019011000 is done.
2019010300 is done.
2018122700 is done.
2018122000 is done.
2018121300 is done.
2018120600 is done.
2018112900 is done.
2018112200 is done.
2018111500 is done.
2018110800 is done.
2018110100 is done.
2018102500 is done.
2018101800 is done.
2018101100 is done.
2018100400 is done.
2018092700 is done.
2018092000 is done.
2018091300 is done.
2018090600 is done.
2018083000 is done.
2018082300 is done.
2018081600 is done.
2018080900 is done.
2018080200 is done.
2018072600 is done.
2018071900 is done.
2018071200 is done.
2018070500 is done.
2018062800 is done.
2018062100 is done.
2018061400 is done.
2018060700 is done.
2018053100 is done.
2018052400 is done.
2018051700 is done.
2018051000 is done.
2018050300 is done.
2018042600 is done.
2018041900 is done.
2018041200 is done.
2018040500 is done.
2018032900 is done.
2018032200 is done.
2018031500 is done.
2018030800 is done.
2018030100 is done.
2018022200 is done.
2018021500 is done.
2018020800 is done.
2018020100 is done.
2018012500 is done.
2018011800 is done.
2018011100 is done.
2018010400 is done.
2017122800 is done.
2017122100 is done.
2017121400 is done.
2017120700 is done.
2017113000 is done.
2017112300 is done.
2017111600 is done.
2017110900 is done.
2017110200 is done.
2017102600 is done.
2017101900 is done.
2017101200 is done.
2017100500 is done.
2017092800 is done.
2017092100 is done.
2017091400 is done.
2017090700 is done.
2017083100 is done.
2017082400 is done.
2017081700 is done.
2017081000 is done.
2017080300 is done.
2017072700 is done.
2017072000 is done.
2017071300 is done.
2017070600 is done.
2017062900 is done.
2017062200 is done.
2017061500 is done.
2017060800 is done.
2017060100 is done.
2017052500 is done.
2017051800 is done.
2017051100 is done.
2017050400 is done.
2017042700 is done.
2017042000 is done.
2017041300 is done.
2017040600 is done.
2017033000 is done.
2017032300 is done.
2017031600 is done.
2017030900 is done.
2017030200 is done.

In [153]:
# 잘 생성되었는지 확인

df1[df1.date == '20170525'][df1.sea == '부산 생도']

C:\Users\edr2\anaconda3\envs\edu\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

            date    sea          htype  percent freq
842     20170525  부산 생도    보름달물해파리_약독성    11.54    2
189749  20170525  부산 생도   노무라입깃해파리_강독성     0.00    0
189750  20170525  부산 생도      유령해파리_강독성     0.00    0
189751  20170525  부산 생도  살파류(척삭동물)_무해성     0.00    0
189752  20170525  부산 생도     오이빗해파리_약독성     0.00    0
189753  20170525  부산 생도    야광원양해파리_강독성     0.00    0
189754  20170525  부산 생도    커튼원양해파리_강독성     0.00    0
189755  20170525  부산 생도    작은상자해파리_맹독성     0.00    0

In [154]:
df2 = df1.sort_values(by=['date','sea', 'htype'])
df2

            date           sea          htype  percent freq
197952  20170302        부산 가덕도   노무라입깃해파리_강독성      0.0    0
197953  20170302        부산 가덕도    보름달물해파리_약독성      0.0    0
197955  20170302        부산 가덕도  살파류(척삭동물)_무해성      0.0    0
197957  20170302        부산 가덕도    야광원양해파리_강독성      0.0    0
197956  20170302        부산 가덕도     오이빗해파리_약독성      0.0    0
...          ...           ...            ...      ...  ...
1119    20220630  부산 해운대청사포 사이    야광원양해파리_강독성      0.0    0
1118    20220630  부산 해운대청사포 사이     오이빗해파리_약독성      0.0    0
1116    20220630  부산 해운대청사포 사이      유령해파리_강독성      0.0    0
1121    20220630  부산 해운대청사포 사이    작은상자해파리_맹독성      0.0    0
1120    20220630  부산 해운대청사포 사이    커튼원양해파리_강독성      0.0    0

[198648 rows x 5 columns]

In [155]:
## csv 파일로 저장

df2.to_csv('해파리주간동향_미출현포함_' + region + '_' + s_y+s_m+s_d + '_' + e_y+e_m+e_d + '.csv', 
          encoding = 'utf-8', index=False)
print('해파리주간동향_미출현포함_' + region + '_' + s_y+s_m+s_d + '_' + e_y+e_m+e_d + '.csv 저장 완료')

해파리주간동향_미출현포함_부산_20170301_20220630.csv 저장 완료

In [156]:
## 잘 불러지는 지 확인

data = pd.read_csv('해파리주간동향_미출현포함_부산_20170301_20220630.csv', encoding = 'utf-8')
data

            date           sea          htype  percent  freq
0       20170302        부산 가덕도   노무라입깃해파리_강독성      0.0     0
1       20170302        부산 가덕도    보름달물해파리_약독성      0.0     0
2       20170302        부산 가덕도  살파류(척삭동물)_무해성      0.0     0
3       20170302        부산 가덕도    야광원양해파리_강독성      0.0     0
4       20170302        부산 가덕도     오이빗해파리_약독성      0.0     0
...          ...           ...            ...      ...   ...
198643  20220630  부산 해운대청사포 사이    야광원양해파리_강독성      0.0     0
198644  20220630  부산 해운대청사포 사이     오이빗해파리_약독성      0.0     0
198645  20220630  부산 해운대청사포 사이      유령해파리_강독성      0.0     0
198646  20220630  부산 해운대청사포 사이    작은상자해파리_맹독성      0.0     0
198647  20220630  부산 해운대청사포 사이    커튼원양해파리_강독성      0.0     0

[198648 rows x 5 columns]