In [1]:
import pandas as pd
import numpy as np
import random
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [36]:
SEED = 2022
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

In [3]:
data1 = pd.read_csv('./data/argumented_jellyfish.csv', encoding='utf-8-sig')
data2 = pd.read_csv('./data/jellyfish2.csv', encoding='utf-8-sig')
display(data1)
display(data2)

,sea,htype,percent,water temperature,salt,temperature,air press,wind direction,wind speed,max wind,precipitation_busan,freq
0,부산 목도,노무라입깃해파리_강독성,16.77,22.032619,32.066726,21.162976,1019.207619,9.005952,1.735655,2.643512,406.892363,1
1,부산 청사포,유령해파리_강독성,1.80,24.038810,31.600357,27.500714,1007.771786,7.089286,1.859643,3.050893,688.800000,1
2,부산 오륙도,노무라입깃해파리_강독성,16.67,26.590833,31.517381,25.794702,1007.467738,11.470238,2.240119,3.703452,406.892363,1
3,부산 가덕도,살파류(척삭동물)_무해성,1.70,18.401429,30.857560,14.796190,1013.823750,9.357143,2.525179,4.189345,1822.800000,1
4,부산 가덕도,노무라입깃해파리_강독성,43.10,22.270119,29.144226,26.236071,1010.003214,3.017857,2.439345,3.475060,1822.800000,1
...,...,...,...,...,...,...,...,...,...,...,...,...
89995,부산 동백섬,보름달물해파리_약독성,19.32,23.365000,32.377560,27.969226,1009.752024,7.440476,2.168452,3.317798,260.431388,2
89996,부산 목도,보름달물해파리_약독성,29.63,26.590833,31.517381,25.794702,1007.467738,11.470238,2.240119,3.703452,406.892363,2
89997,부산 광안리,보름달물해파리_약독성,27.88,18.935417,33.739821,21.841607,1007.747321,7.172619,1.788393,2.752917,231.510614,0
89998,부산 영도,노무라입깃해파리_강독성,62.70,24.038810,31.600357,27.500714,1007.771786,7.089286,1.859643,3.050893,688.800000,2
89999,부산 북형제도,노무라입깃해파리_강독성,49.50,25.388452,29.418929,25.985655,1007.949821,4.184524,2.773274,4.186905,1822.800000,2

,date,sea,htype,percent,water temperature,salt,temperature,air press,wind direction,wind speed,max wind,precipitation_busan,freq
0,2017-06-08,부산 가덕도,노무라입깃해파리_강독성,0.0,17.349940,33.995893,18.794524,1009.508155,8.041667,2.498155,3.857917,231.510614,0
1,2017-06-08,부산 가덕도,보름달물해파리_약독성,0.0,17.349940,33.995893,18.794524,1009.508155,8.041667,2.498155,3.857917,231.510614,0
2,2017-06-08,부산 가덕도,살파류(척삭동물)_무해성,0.0,17.349940,33.995893,18.794524,1009.508155,8.041667,2.498155,3.857917,231.510614,0
3,2017-06-08,부산 가덕도,야광원양해파리_강독성,0.0,17.349940,33.995893,18.794524,1009.508155,8.041667,2.498155,3.857917,231.510614,0
4,2017-06-08,부산 가덕도,오이빗해파리_약독성,0.0,17.349940,33.995893,18.794524,1009.508155,8.041667,2.498155,3.857917,231.510614,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
91843,2021-12-02,부산 해운대청사포 사이,야광원양해파리_강독성,0.0,14.384981,33.086647,9.335919,1022.817887,9.231138,2.134277,3.335022,1822.800000,0
91844,2021-12-02,부산 해운대청사포 사이,오이빗해파리_약독성,0.0,14.384981,33.086647,9.335919,1022.817887,9.231138,2.134277,3.335022,1822.800000,0
91845,2021-12-02,부산 해운대청사포 사이,유령해파리_강독성,0.0,14.384981,33.086647,9.335919,1022.817887,9.231138,2.134277,3.335022,1822.800000,0
91846,2021-12-02,부산 해운대청사포 사이,작은상자해파리_맹독성,0.0,14.384981,33.086647,9.335919,1022.817887,9.231138,2.134277,3.335022,1822.800000,0
91847,2021-12-02,부산 해운대청사포 사이,커튼원양해파리_강독성,0.0,14.384981,33.086647,9.335919,1022.817887,9.231138,2.134277,3.335022,1822.800000,0

In [39]:
labelencoder=LabelEncoder()
for col in data1.columns:
    data1[col] = labelencoder.fit_transform(data1[col])
for col in data2.columns:
    data2[col] = labelencoder.fit_transform(data2[col])
display(data1)
display(data2)

,sea,htype,percent,water temperature,salt,temperature,air press,wind direction,wind speed,max wind,precipitation_busan,freq
0,79,5,28,30,108,9,101,75,108,102,7,1
1,53,5,17,72,58,36,107,123,56,73,3,1
2,0,1,197,122,72,113,38,83,93,112,5,1
3,56,0,36,50,104,56,42,70,81,82,0,1
4,9,0,154,67,34,35,105,118,28,44,9,1
...,...,...,...,...,...,...,...,...,...,...,...,...
29995,25,0,253,104,45,117,34,47,24,28,6,2
29996,59,0,250,70,2,118,64,30,91,67,6,2
29997,75,0,250,70,2,118,64,30,91,67,6,2
29998,53,0,229,119,63,115,14,14,121,118,3,2
29999,53,0,225,49,19,52,5,102,27,32,6,2

,date,sea,htype,percent,water temperature,salt,temperature,air press,wind direction,wind speed,max wind,precipitation_busan,freq
0,0,0,0,0,25,125,34,51,63,83,85,2,0
1,0,0,1,0,25,125,34,51,63,83,85,2,0
2,0,0,2,0,25,125,34,51,63,83,85,2,0
3,0,0,3,0,25,125,34,51,63,83,85,2,0
4,0,0,4,0,25,125,34,51,63,83,85,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
91843,128,88,3,0,0,92,1,127,81,49,46,9,0
91844,128,88,4,0,0,92,1,127,81,49,46,9,0
91845,128,88,5,0,0,92,1,127,81,49,46,9,0
91846,128,88,6,0,0,92,1,127,81,49,46,9,0
91847,128,88,7,0,0,92,1,127,81,49,46,9,0

In [40]:
x1 = data1.iloc[:, :-1].values
y1 = data1.iloc[:, -1:].values
display(x1)
x1_train , x1_test , y1_train , y1_test = train_test_split(x1, y1, test_size=0.2, random_state=42)
y1_train = tf.keras.utils.to_categorical(y1_train, num_classes=3)
y1_test = tf.keras.utils.to_categorical(y1_test, num_classes=3)

x2 = data2.iloc[:, 1:-1].values
y2 = data2.iloc[:, -1:].values
display(x2)
x2_train , x2_test , y2_train , y2_test = train_test_split(x2, y2, test_size=0.2, random_state=42)
y2_train = tf.keras.utils.to_categorical(y2_train, num_classes=4)
y2_test = tf.keras.utils.to_categorical(y2_test, num_classes=4)

array([[ 79,   5,  28, ..., 108, 102,   7],
       [ 53,   5,  17, ...,  56,  73,   3],
       [  0,   1, 197, ...,  93, 112,   5],
       ...,
       [ 75,   0, 250, ...,  91,  67,   6],
       [ 53,   0, 229, ..., 121, 118,   3],
       [ 53,   0, 225, ...,  27,  32,   6]])

array([[ 0,  0,  0, ..., 83, 85,  2],
       [ 0,  1,  0, ..., 83, 85,  2],
       [ 0,  2,  0, ..., 83, 85,  2],
       ...,
       [88,  5,  0, ..., 49, 46,  9],
       [88,  6,  0, ..., 49, 46,  9],
       [88,  7,  0, ..., 49, 46,  9]])

In [41]:
model1 = tf.keras.Sequential([
    tf.keras.layers.Dense(units=48, activation='relu', input_shape = x1_train[0].shape),    
    tf.keras.layers.Dense(units=24, activation='relu'),                                     
    tf.keras.layers.Dense(units=12, activation='relu'),                                     
    tf.keras.layers.Dense(units=3, activation='softmax')                                    
])
model1.compile(optimizer=tf.keras.optimizers.Adam(learning_rate = 0.001),
              loss = 'categorical_crossentropy',
              metrics = ['accuracy'])


model2 = tf.keras.Sequential([
    tf.keras.layers.Dense(units=64, activation='relu', input_shape = x2_train[0].shape),     
    tf.keras.layers.Dense(units=32, activation='relu'),                                     
    tf.keras.layers.Dense(units=16, activation='relu'),                                     
    tf.keras.layers.Dense(units=4, activation='softmax')                                    
])
model2.compile(optimizer=tf.keras.optimizers.Adam(learning_rate = 0.001),
              loss = 'categorical_crossentropy',
              metrics = ['accuracy'])

model1.summary()
model2.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_16 (Dense)            (None, 48)                576

 dense_17 (Dense)            (None, 24)                1176

 dense_18 (Dense)            (None, 12)                300

 dense_19 (Dense)            (None, 3)                 39

=================================================================
Total params: 2,091
Trainable params: 2,091
Non-trainable params: 0
_________________________________________________________________
Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_20 (Dense)            (None, 64)                768

 dense_21 (Dense)            (None, 32)                2080

 dense_22 (Dense)            (None, 16)                528

 dense_23 (Dense)            (None, 4)                 68

=================================================================
Total params: 3,444
Trainable params: 3,444
Non-trainable params: 0
_________________________________________________________________

In [42]:
model1.fit(x1_train, y1_train, epochs=25, batch_size=32, validation_split=0.2, callbacks=[tf.keras.callbacks.EarlyStopping(patience=3, monitor='val_loss')])

Epoch 1/25
600/600 [==============================] - 2s 3ms/step - loss: 1.9028 - accuracy: 0.6602 - val_loss: 0.5757 - val_accuracy: 0.7283
Epoch 2/25
600/600 [==============================] - 2s 3ms/step - loss: 0.5324 - accuracy: 0.7448 - val_loss: 0.5027 - val_accuracy: 0.7525
Epoch 3/25
600/600 [==============================] - 1s 2ms/step - loss: 0.4576 - accuracy: 0.7762 - val_loss: 0.3991 - val_accuracy: 0.8077
Epoch 4/25
600/600 [==============================] - 1s 2ms/step - loss: 0.4309 - accuracy: 0.7927 - val_loss: 0.4418 - val_accuracy: 0.7948
Epoch 5/25
600/600 [==============================] - 1s 2ms/step - loss: 0.4053 - accuracy: 0.8072 - val_loss: 0.3632 - val_accuracy: 0.8213
Epoch 6/25
600/600 [==============================] - 1s 2ms/step - loss: 0.3862 - accuracy: 0.8136 - val_loss: 0.3736 - val_accuracy: 0.8081
Epoch 7/25
600/600 [==============================] - 1s 2ms/step - loss: 0.3697 - accuracy: 0.8214 - val_loss: 0.3251 - val_accuracy: 0.8377
Epoch 8/25
600/600 [==============================] - 1s 2ms/step - loss: 0.3559 - accuracy: 0.8289 - val_loss: 0.3178 - val_accuracy: 0.8358
Epoch 9/25
600/600 [==============================] - 1s 2ms/step - loss: 0.3563 - accuracy: 0.8311 - val_loss: 0.3201 - val_accuracy: 0.8429
Epoch 10/25
600/600 [==============================] - 1s 2ms/step - loss: 0.3381 - accuracy: 0.8356 - val_loss: 0.3797 - val_accuracy: 0.8148
Epoch 11/25
600/600 [==============================] - 2s 3ms/step - loss: 0.3249 - accuracy: 0.8426 - val_loss: 0.3033 - val_accuracy: 0.8492
Epoch 12/25
600/600 [==============================] - 2s 3ms/step - loss: 0.3187 - accuracy: 0.8449 - val_loss: 0.3112 - val_accuracy: 0.8404
Epoch 13/25
600/600 [==============================] - 1s 2ms/step - loss: 0.3130 - accuracy: 0.8494 - val_loss: 0.2959 - val_accuracy: 0.8592
Epoch 14/25
600/600 [==============================] - 2s 3ms/step - loss: 0.3060 - accuracy: 0.8520 - val_loss: 0.3198 - val_accuracy: 0.8381
Epoch 15/25
600/600 [==============================] - 1s 2ms/step - loss: 0.2959 - accuracy: 0.8577 - val_loss: 0.3428 - val_accuracy: 0.8381
Epoch 16/25
600/600 [==============================] - 2s 3ms/step - loss: 0.2865 - accuracy: 0.8609 - val_loss: 0.2718 - val_accuracy: 0.8631
Epoch 17/25
600/600 [==============================] - 1s 2ms/step - loss: 0.2829 - accuracy: 0.8622 - val_loss: 0.2813 - val_accuracy: 0.8619
Epoch 18/25
600/600 [==============================] - 1s 2ms/step - loss: 0.2770 - accuracy: 0.8648 - val_loss: 0.2771 - val_accuracy: 0.8631
Epoch 19/25
600/600 [==============================] - 2s 3ms/step - loss: 0.2656 - accuracy: 0.8696 - val_loss: 0.2833 - val_accuracy: 0.8606

In [43]:
model1.evaluate(x1_test, y1_test)

188/188 [==============================] - 1s 2ms/step - loss: 0.2745 - accuracy: 0.8658

[0.2744750678539276, 0.8658333420753479]

In [44]:
model2.fit(x2_train, y2_train, epochs=10, batch_size=32, validation_split=0.2, callbacks=[tf.keras.callbacks.EarlyStopping(patience=3, monitor='val_loss')])

Epoch 1/10
1837/1837 [==============================] - 5s 3ms/step - loss: 0.1348 - accuracy: 0.9903 - val_loss: 0.0184 - val_accuracy: 0.9952
Epoch 2/10
1837/1837 [==============================] - 5s 2ms/step - loss: 0.0122 - accuracy: 0.9963 - val_loss: 0.0112 - val_accuracy: 0.9963
Epoch 3/10
1837/1837 [==============================] - 5s 2ms/step - loss: 0.0100 - accuracy: 0.9965 - val_loss: 0.0072 - val_accuracy: 0.9964
Epoch 4/10
1837/1837 [==============================] - 4s 2ms/step - loss: 0.0095 - accuracy: 0.9964 - val_loss: 0.0089 - val_accuracy: 0.9965
Epoch 5/10
1837/1837 [==============================] - 6s 3ms/step - loss: 0.0086 - accuracy: 0.9967 - val_loss: 0.0104 - val_accuracy: 0.9955
Epoch 6/10
1837/1837 [==============================] - 10s 5ms/step - loss: 0.0077 - accuracy: 0.9968 - val_loss: 0.0080 - val_accuracy: 0.9964

In [45]:
model2.evaluate(x2_test, y2_test)

575/575 [==============================] - 2s 4ms/step - loss: 0.0093 - accuracy: 0.9964

[0.009261881932616234, 0.9964072108268738]

------

In [46]:
prediction1 = model1.predict(x1_test)
pred_result1 = tf.argmax(prediction1,axis=1)
pred_result1 = pred_result1.numpy()
display(pred_result1)

array([0, 1, 2, ..., 2, 1, 2])

In [47]:
print(len(pred_result1[pred_result1==0]))
print(len(pred_result1[pred_result1==1]))
print(len(pred_result1[pred_result1==2]))
#print(np.count_nonzero(pred_result1))

122
3960
1918

In [48]:
prediction2 = model2.predict(x2_test)
pred_result2 = tf.argmax(prediction2,axis=1)
pred_result2 = pred_result2.numpy()
display(pred_result2)

array([0, 0, 0, ..., 0, 0, 0])

In [49]:
print(len(pred_result2[pred_result2==0]))
print(np.count_nonzero(pred_result2))

18207
163